# Generated by Django 2.2.13 on 2021-08-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='diary',
        ),
        migrations.AlterModelTable(
            name='diary',
            table='diary',
        ),
    ]
