# Generated by Django 2.2.13 on 2021-08-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210815_0037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='Article',
        ),
    ]
