# Generated by Django 2.2.13 on 2021-08-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210815_0038'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='comment',
        ),
    ]
