# Generated by Django 2.2.13 on 2021-08-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20210815_0043'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
